projeto2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
]

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('create', views.RecipeCreate.as_view(), name='create'),
    path('recipes', views.RecipeList.as_view(), name='recipes'),
    path('recipes/<int:pk>', views.RecipeDetails.as_view(), name='recipe_detail'),
    path('delete/<int:pk>', views.RecipeDeleteConfirm.as_view(), name='delete'),
    path('update/<int:pk>', views.RecipeUpdate.as_view(), name='update'),
    path('comment/create/<int:pk>', views.CommentCreate, name='create_comment'),
    path('categories', views.CategoryList, name='categories'),
    path('categories/<int:pk>', views.CategoryDetail, name='category_detail'),
]

recipes/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    picture = models.URLField(max_length=200, null=True, blank=True)
    ingredients = models.TextField(max_length=5000)
    making = models.TextField(max_length=5000)
    content = models.TextField(max_length=5000)
    description = models.TextField(max_length=255, null=True, blank=True)
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}: Postado em {self.post_date}'

    def save(self, *args, **kwargs):
        self.content = '<h2>Ingredientes</h2>\n<ul>\n'
        for ing in self.ingredients.splitlines():
            if ing == '':
                pass
            elif ing[0] == '-':
                self.content += f'    <li>{ing[1:]}\n'
            else:
                if self.content[-5:] == '<ul>\n':
                    self.content = self.content[:-5]
                self.content += f'<h3>{ing}</h3>\n'
        self.content += '</ul>\n<br>\n<h2>Modo de preparo</h2>\n<p>\n'
        for line in self.making.splitlines():
            self.content += f'{line}\n<br>'
        self.content += '\n</p>'
        super().save(*args, **kwargs)

class Comment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    text = models.TextField(max_length=5000)
    post_date = models.DateTimeField(auto_now_add=True)
    recipe = models.ForeignKey(Post, on_delete=models.CASCADE)

Comment.objects.order_by('post_date')

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    recipe = models.ManyToManyField(Post)

recipes/forms.py
from django.db.models import fields
from django.db.models.base import Model
from django.forms import ModelForm, widgets, CharField
from .models import *

class RecipeForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'picture',
            'ingredients',
            'making',
            'description',
        ]
        labels = {
            'title': 'Título da postagem',
            'picture': 'URL da imagem',
            'ingredients': 'Ingredientes da receita',
            'making': 'Modo de preparo',
            'description': 'Descrição da receita',
        }
        widgets = {
            'ingredients': widgets.Textarea(attrs={'cols': 50, 'rows': 10}),
            'making': widgets.Textarea(attrs={'cols': 50, 'rows': 10}),
            'description': widgets.Textarea(attrs={'cols': 50, 'rows': 10}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'text']
        labels = {
            'author': 'Autor',
            'text': 'Comentário',
        }
        widgets = {
            'text': widgets.Textarea(attrs={'cols': 50, 'rows': 10}),
        }

recipes/views.py
from random import choice
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import *
from .forms import *

# Create your views here.
def index(req):
    vegetariano = list(Category.objects.get(name='Vegetarianos').recipe.exclude(description__isnull=True).exclude(description__exact=''))
    carne = list(Category.objects.get(name='Carnes').recipe.exclude(description__isnull=True).exclude(description__exact=''))
    sobremesa = list(Category.objects.get(name='Sobremesa').recipe.exclude(description__isnull=True).exclude(description__exact=''))

    pratos = {
        'vegetariano': choice(vegetariano),
        'sobremesa': choice(sobremesa)
        }

    vegetariano.remove(pratos['vegetariano'])
    dia = vegetariano + carne

    pratos.update({'dia': choice(dia)})

    return render(req, 'recipes/index.html', context={'prato': pratos})

def about(req):
    return render(req, 'recipes/about.html', context={})

class RecipeList(generic.ListView):
    model = Post
    template_name = 'recipes/list.html'
    context_object_name = 'recipes'

class RecipeDetails(generic.DetailView):
    model = Post
    template_name = 'recipes/recipe.html'
    context_object_name = 'recipe'

class RecipeCreate(generic.CreateView):
    model = Post
    form_class = RecipeForm
    template_name = 'recipes/create.html'

    def get_success_url(self):
        return reverse('recipe_detail', args=(self.object.id,))
    
class RecipeUpdate(generic.UpdateView):
    model = Post
    form_class = RecipeForm
    template_name = 'recipes/create.html'
    
    def get_initial(self):
        recipe = self.object
        initial = {
            'title': recipe.title,
            'picture': recipe.picture,
            'content': recipe.content,
            'description': recipe.description,
        }
        return initial

    def get_success_url(self):
        return reverse('recipe_detail', args=(self.object.id,))

class RecipeDeleteConfirm(generic.DeleteView):
    model = Post
    template_name = 'recipes/delete.html'
    success_url = reverse_lazy('recipes')
    context_object_name = 'recipe'

def CommentCreate(req, pk):
    recipe = get_object_or_404(Post, id=pk)
    if req.method == 'POST':
        form = CommentForm(req.POST)
        if form.is_valid():
            author = form.cleaned_data['author']
            text = form.cleaned_data['text']
            comment = Comment(author=author, text=text, recipe=recipe)
            comment.save()
            return HttpResponseRedirect(reverse('recipe_detail', args=(pk, )))
    else:
        form = CommentForm()
    return render(req, 'recipes/comment.html', context={'form': form, 'recipe': recipe})

def CategoryDetail(req, pk):
    category = get_object_or_404(Category, id=pk) 
    return render(req, 'recipes/list.html', context={'recipes': category.recipe.all(), 'title': category.name, 'description': category.description})

def CategoryList(req):
    return render(req, 'recipes/categories.html', context={'categories': Category.objects.all()})

recipes/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>
            Cozinha & Sabor - {% block title %} {% endblock %}
        </title>
    </head>
<body>
    <header>
        <img src="{% static 'logo.png' %}" alt="logo" width="80">
            <h1>Cozinha & Sabor</h1>
            
            <nav id="header-buttons">
                <a href="{% url 'index' %}" class="button">Inicial</a>
                <a href="{% url 'recipes' %}" class="button">Receitas</a>
                <a href="{% url 'categories' %}" class="button">Categorias</a>
                <a href="{% url 'about' %}" class="button">Sobre</a>
            </nav>
    </header>

    <main>
        <hr>
        {% block content %}
        {% endblock content %}
    </main>

    <footer>
        <p>Copyright 2021 Rafael Yudi Tanino.</p>
    </footer>
</body>
</html>

recipes/templates/recipes/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre</h2>
<h4>
    Esta página foi criada por Rafael Yudi Tanino, para a disciplina "PMR3304 - Sistemas de Informação", sendo uma forma de colocar em prática o que foi visto
    durante as aulas de laboratório, em especial sobre assuntos de páginas dinâmica, como:
</h4>
<ul>
    <li>Django</li>
    <li>HTTP</li>
    <li>SQL e ORM</li>
    <li>CRUD</li>
</ul>
{% endblock content %}

recipes/templates/recipes/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias</h2>
<div id='list-page'>
    <ul id="lista-receitas">
        {% for category in categories %}
        <li><a class="button receitas" href="{% url 'category_detail' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

recipes/templates/recipes/comment.html
{% extends 'base.html' %}

{% block title %}
Postar comentário
{% endblock title %}

{% block content %}
<h2>Postar comentário sobre {{ recipe.title }}</h2>
<div class="form">

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="form-button" type="submit">Postar</button>
    </form>
</div>
{% endblock content %}

recipes/templates/recipes/create.html
{% extends 'base.html' %}

{% block title %}
Postar nova receita
{% endblock title %}

{% block content %}
<h2>Postar nova receita</h2>
<div class="form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="form-button" type="submit">Postar</button>
    </form>
</div>
{% endblock content %}

recipes/templates/recipes/delete.html
{% extends 'base.html' %}

{% block title %}
Remover postagem
{% endblock title %}

{% block content %}
<h2>Remover postagem</h2>
<p>Deseja realmente excluir <strong>permanentemente</strong> esta postagem ({{ recipe.title }})?</p>

<div id='delete-buttons'>
    <form method="post">
        {% csrf_token %}
        <button class="button delete-confirm" type="submit">Excluir</button>
    </form>
    <a class="button delete-cancel" href="{% url 'recipe_detail' recipe.id %}">Retornar à postagem</a>
</div>
{% endblock content %}

recipes/templates/recipes/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<section id="homepage">

    <article id="prato-do-dia">
        <h2 class="title">Prato do Dia</h2>
        <div class="conteudo-prato">

            <div id="espaco-foto-dia">
                <a href="{% url 'recipe_detail' prato.dia.id %}">
                    <img class="foto-dia" src='{{ prato.dia.picture }}' alt="{{ prato.dia.title }}" height="380">
                </a>
            </div>

            <div class="prato">
                <h1 id="dia-titulo"><a href="{% url 'recipe_detail' prato.dia.id %}">
                    {{ prato.dia.title }}
                </a></h1>

                <p id="dia-texto">
                    {{ prato.dia.description }}
                </p>
            </div>

        </div>
    </article>

    <section id="pratos">
        <article id="home-veg">
            <h1 class="title">Vegetariano</h1>
            <div class="conteudo-prato">

                <div class="espaco-foto">
                    <a href="{% url 'recipe_detail' prato.vegetariano.id %}">
                        <img class="foto-veg" src='{{ prato.vegetariano.picture }}' alt="{{ prato.vegetariano.title }}" height="200">
                    </a>
                </div>

                <div class="prato">
                    <h4><a href="{% url 'recipe_detail' prato.vegetariano.id %}">
                        {{ prato.vegetariano.title }}
                    </a></h4>

                    <p class="texto-prato">
                        {{ prato.vegetariano.description }}
                    </p>
                </div>
            </div>
        </article>
        
        <article id="home-sobremesa">
            <h1 class="title">Sobremesa</h1>
            <div class="conteudo-prato">

                <div class="espaco-foto">
                    <a href="{% url 'recipe_detail' prato.sobremesa.id %}">
                        <img class="foto-sobremesa" src='{{ prato.sobremesa.picture }}' alt="{{ prato.sobremesa.title }}" height="200">
                    </a>
                </div>

                <div class="prato">
                    <h4><a href="{% url 'recipe_detail' prato.sobremesa.id %}">
                        {{ prato.sobremesa.title }}
                    </a></h4>
                    
                    <p class="texto-prato">
                        {{ prato.sobremesa.description }}
                    </p>
                </div>
            </div>
        </article>
    </section>

</section>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'base.html' %}

{% block title %}
Receitas
{% endblock title %}

{% block content %}
{% if title %}
    <h2>Receitas - {{ title }}</h2>
    <p>{{ description }}</p>
{% else %}
    <h2>Receitas</h2>
{% endif %}
<div id='list-page'>
    <ul id="lista-receitas">
        {% for receita in recipes %}
        <li><a class="button receitas" href="{% url 'recipe_detail' receita.id %}">{{ receita.title }}</a></li>
        {% endfor %}
    </ul>
    {% if not title %}
        <a href="{% url 'create' %}" class='button post'>Adicionar nova receita</a>
    {% endif %}
</div>
{% endblock content %}

recipes/templates/recipes/recipe.html
{% extends 'base.html' %}

{% block title %}
{{ recipe.title }}
{% endblock title %}

{% block content %}
<h2>{{ recipe.title }}</h2>
<div id='top-recipe-page'>
    <p id='post-info'>--Postado em {{ recipe.post_date|date:"d b Y" }}--</p>
    <div id='top-recipe-page-buttons'>
        <a href="{% url 'update' recipe.id %}" class='button update'>Modificar postagem</a>
        <a href="{% url 'delete' recipe.id %}" class='button delete'>Excluir postagem</a>
    </div>
</div>
{% if recipe.category_set.all %}
<div id="categories">
    <h3>Categorias</h3>
    <ul id="lista-receitas">
        {% for cat in recipe.category_set.all %}
            <li><a href="{% url 'category_detail' cat.id %}">{{ cat.name }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<img class='center-image' src="{{ recipe.picture }}" alt="Foto - {{ recipe.title }}" height="500">
<br>
{{ recipe.content|safe }}

<hr>
<br>
<section id="comments">
    <div id="comments-header">
        <h2 id="comments-title">Comentários</h2>
        <a href="{% url 'create_comment' recipe.id %}" class='button create-comment'>Adicionar novo comentário</a>
    </div>
    <br>
    {% if recipe.comment_set.all %}
        {% for comment in recipe.comment_set.all %}
        <div class="comment">
            <h4>{{ comment.author }}:</h4>
            <p class="comment-text">{{ comment.text }}</p>
            <p class="comment-date">{{ comment.post_date|date:"d b Y" }}</p>
        </div>
        {% endfor %}
    {% else %}
        <p>Não há comentários para esta receita.</p>
    {% endif %}
    
    {% endblock content %}
</section>

recipes/templates/recipes/update.html
{% extends 'base.html' %}

{% block title %}
Modificar receita - {{ recipe.title }}
{% endblock title %}

{% block content %}
<h2>Modificar receita de {{ recipe.title }}</h2>
<div class="form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="form-button" type="submit">Salvar</button>
    </form>
</div>
{% endblock content %}